# Generated by Django 2.1.7 on 2019-04-14 21:16

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='Books/books-default.jpg', upload_to=items.models.img_directory_path),
        ),
    ]
