# Generated by Django 2.1.7 on 2019-04-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190415_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
