# Generated by Django 2.1.7 on 2019-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20190415_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='Books/', null=True, upload_to='uploads/books/'),
        ),
    ]
