# Generated by Django 2.1.7 on 2019-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20190422_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='Books/books-default.jpg', null=True, upload_to='uploads/books/'),
        ),
    ]
